### ISSUE TITLE
feature request: modularize gene-level summarization when txOut=TRUE

### ISSUE THREAD

**Issue by stephenturner** [mikelove/tximport#12]
I wanted to use tximport to read in a bunch of sailfish output files then write out abundances/counts for both genes _and_ transcripts. I ended up doing the import twice, once for txOut=TRUE and once where it was FALSE. Would be nice to allow usage where txOut=FALSE, then apply a later function that would perform the summarization as a separate step.

e.g.

```r
txdata <- tximport(files, txOut=FALSE)
gndata <- txGeneSum(txdata)
```

**Comment by mikelove** [comment]
makes sense. I'll think on restructuring the code.

**Comment by mikelove** [comment]
hi Stephen, 

good suggestion. helped me to shorten average function length while i'm at it.

when you have time, try out version 0.0.19 with `summarizeToGene`. example in the beginning of the vignette.
