### ISSUE TITLE
Unexpected behavior when processing RSEM transcript level files

### ISSUE THREAD

**Issue by ecoenen** [mikelove/tximport#15]
I used this line of code to process RSEM ".isoforms.results" files:
txi.RSEM <- tximport(files, type = "rsem", reader = read_tsv, txIn = TRUE, txOut = TRUE)
The rownames of the resulting list objects, are gene ID's, which is not what I expected, since I put the txOut option to true.

When I explicitly define the column names like in the line of code below, it works like expected (the rownames of the resulting list objects are now transcript ID's):
txi.RSEM <- tximport(files, type = "none", geneIdCol = "gene_id", txIdCol = "transcript_id",
                     abundanceCol = "TPM", countsCol = "expected_count", lengthCol = "length", reader =     
                       read_tsv, txIn = TRUE, importer = read.delim, txOut = TRUE)

**Comment by mikelove** [comment]
Yup. I haven't had time to work on this, but I had already filed it as an issue to remind myself:

https://github.com/mikelove/tximport/issues/11

Bioconductor is in feature freeze right now in preparation for a new release. But this is on my short list of issue to address next cycle.
