### ISSUE TITLE
Check for existence of abundance.h5 before checking for rhdf5?

### ISSUE THREAD

**Issue by csoneson** [mikelove/tximport#21]
Currently the check for the presence of `rhdf5` precedes the check of whether there is actually an `abundance.h5` file to read (in `readInfRepKallisto`). This might cause errors in situations where one has only the `abundance.tsv` file, `rhdf5` is not available, and one doesn't set `dropInfReps=TRUE`.

**Comment by mikelove** [comment]
Fixed in 22a5f2a1175e71254536cce17be29b22fd6d1b56
