### ISSUE TITLE
sparse matrix support?

### ISSUE THREAD

**Issue by koenvandenberge** [mikelove/tximport#25]
I was wondering whether it would possible to support sparse matrices as output of tximport.
This might make tximport more attractive for people working with scRNA-seq data.

I'm currently running into problems when importing >400 single cells because of memory limits.
Since the memory issues occur while importing the cells, converting the data to sparse format based on the `SummarizedExperiment` would not help because I can't get up to that point yet.

A current solution is to import the data in parts, and convert those to sparse matrices.

**Comment by mikelove** [comment]
Interesting problem. So sparsifying the largest chunk possible and then combining is probably the implementation to beat in terms of speed. To think out loud, the sparse version would import the nonzero element and indices and then Matrix::sparseMatrix to create the matrix, right? I wonder if they’ve already implemented this in the SingleCellExperwnr codebase or if it would go here already.

**Comment by roryk** [comment]
Heya-- I've looked at datasets at around a million cells using Seurat, and the memory blows up when fitting models to that many cells; the initial importing I think is just the first and one of the least memory intensive portions of what DESeq2 will end up doing with the data, so sparsing it just might  solve that one problem but not help getting much further.

We've looked at thousands of cells with DESeq2 and it seems to work fine, but you do need a bunch of memory to get it working.

**Comment by koenvandenberge** [comment]
Yes, importing the nonzero element values and indices would probably be a good idea. 
I guess it could be relatively simple by selecting the non-zero elements in the last column of the quant.sf files.
Then the only thing we need is a vector with feature names and a vector with column names for the matrix.

I think that the `SingleCellExperiment` framework could be good as output, since it also builds on `SummarizedExperiment` but accepts sparse matrices. But then there's the problem of when tximport should return a `SingleCellExperiment` rather than a `SummarizedExperiment` ...

I'm often still working locally on my 16GB RAM laptop. While I agree that I won't be able to run DESeq2 on thousands of cells, I think that importing them in sparse matrix format should be possible. I think that it is a good thing to be optimistic and hope that in due time fast and memory-efficient methods will be around to process those datasets, even on a local machine. For now, I just wanted to make some plots :-).

**Comment by mikelove** [comment]
Setting aside the inference stuff (we're working on this, but side topic), we've tried to set it up so *tximport* has no dependencies to encourage broad adoption (developers don't want too many upstream dependencies) and *tximeta* builds the rich S4 objects. So I'm thinking *tximport* would give back a more basic object like a sparse matrix as implemented in *Matrix* package (and this would only be a Suggests). I think I can whip this up soon-ish. Meanwhile, we also are looking into *tximport* importing `alevin` output, which I should also find time to implement.

It seems simple enough for the point estimates, but would take some more time for the inferential replicates.

**Comment by roryk** [comment]
Happy to help out testing which works faster.

**Comment by pinin4fjords** [comment]
Sorry to butt in on this old thread, but I'm currently trying (possibly foolishly) to aggregate the results of 50k Kallisto runs with tximport- with the older non-sparse version of tximport. I gave up when the memory topped 150Gb on our cluster before failing.

Is this something the sparse options are likely to deal with effectively, or are these numbers far beyond what tximport can sensibly deal with?

**Comment by mikelove** [comment]
You can try e.g. 10 samples with and without `sparse=TRUE` to see what your savings will be with sparsity.

Likely you need to find another approach that doesn't involve creating an in-memory matrix that is 20k x 50k

**Comment by pinin4fjords** [comment]
Okay that's useful- thanks.

**Comment by lambdamoses** [comment]
I'm working with some alevin output, and even not so large datasets would run out of memory because a dense matrix is returned. It seems that the `sparse` argument does not affect alevin: https://github.com/mikelove/tximport/blob/d1a195b41f92489562f451ecf99f8fd6d47bb112/R/tximport.R#L201-L214. Is there any way to read the alevin binary for the matrix as a sparse matrix? I guess that might require you to write some custom Rcpp code.

**Comment by rob-p** [comment]
cc @k3yavi --- I think we should bump the priority of having a sparse-matrix pipeline from alevin -> tximport.

**Comment by mikelove** [comment]
Let’s doooo it. 🤘

**Comment by lambdamoses** [comment]
I'm doing it right now. If it works well, I'll PR

**Comment by mikelove** [comment]
@lambdamoses we are planning to change the output format to make it massively smaller on disk and faster and more efficient to read as well

**Comment by lambdamoses** [comment]
Do you mean that you are changing the alevin binary matrix output so it's a sparse matrix? That would be great!

**Comment by rob-p** [comment]
@lambdamoses : Yes, we are planning on having alevin output sparse (and compressed) matrices directly so that they can be directly read as sparse matrices into R, either via some existing library function or via some (hopefully trivial) function that we implement.

**Comment by pinin4fjords** [comment]
I adapted @k3yavi's Alevin parser to make 10X-style matrix market format via a sparse python matrix. I put in on the gitter channel here a couple of days ago: https://gitter.im/COMBINE-lab/salmon (disclaimer: not thoroughly tested yet, it's part of a new and currently private internal repo). That format is nicely parsable by DropletUtils etc in R, straight to a SingleCellExperiment.

**Comment by lambdamoses** [comment]
Before alevin and tximport support sparse matrices, you can use this script to read alevin output as a sparse matrix:

```r
#' Read salmon alevin binary output as sparse matrix
#' 
#' The most annoying part about alevin: all available methods to load the binary
#' output return a dense matrix, which is a huge waste of memory. Here I try to
#' load it as a sparse matrix.
#' 
#' @param files Directory with the salmon alevin output.
#' @param save_mtx Logical, whether the sparse matrix should be saved as a mtx
#' file. If \code{FALSE}, then a dgCMatrix is returned.
#' @param save_path Where to save the mtx file. If \code{save_mtx = TRUE}, then
#' this argument must be specified. If the directory doesn't exist, then it will
#' be created.
#' @param \dots Other arguments passed to \code{BUSpaRse::save_cellranger}.
#' @return If \code{save_mtx = FALSE}, then a dgCMatrix with cells in columns 
#' and genes in rows, with barcodes as column names and gene IDs as row names.
#' Otherwise, 3 files will be written to the directory specified in \code{save_path}:
#' matrix.mtx.gz, features.tsv.gz, and barcodes.tsv.gz, and the dgCMatrix is returned
#' invisibly.
#' 
readAlevin_sparse <- function(files, save_mtx = FALSE, save_path = NULL,
                              ...) {
  dir <- sub("/alevin$","",dirname(files))
  barcode.file <- file.path(dir, "alevin/quants_mat_rows.txt")
  gene.file <- file.path(dir, "alevin/quants_mat_cols.txt")
  matrix.file <- file.path(dir, "alevin/quants_mat.gz")
  for (f in c(barcode.file, gene.file, matrix.file)) {
    if (!file.exists(f)) {
      stop("expecting 'files' to point to 'quants_mat.gz' file in a directory 'alevin'
           also containing 'quants_mat_rows.txt' and 'quant_mat_cols.txt'.
           please re-run alevin preserving output structure")
    }
  }
  cell.names <- readLines(barcode.file)
  gene.names <- readLines(gene.file)
  num.cells <- length(cell.names)
  num.genes <- length(gene.names)
  #mat <- matrix(nrow=num.genes, ncol=num.cells, dimnames=list(gene.names, cell.names))
  values <- rowinds <- colinds <- vector("list", num.cells)
  con <- gzcon(file(matrix.file, "rb"))
  pb <- txtProgressBar(style = 3, max = num.cells)
  for (j in seq_len(num.cells)) {
    v <- readBin(con, double(), endian = "little", n=num.genes)
    non0_inds <- which(v > 0)
    values[[j]] <- v[non0_inds]
    rowinds[[j]] <- non0_inds
    colinds[[j]] <- rep(j, length(non0_inds))
    setTxtProgressBar(pb, j)
  }
  close(pb)
  close(con)
  values <- unlist(values)
  rowinds <- unlist(rowinds)
  colinds <- unlist(colinds)
  mat <- sparseMatrix(i = rowinds, j = colinds, x = values, 
                      dims = c(num.genes, num.cells),
                      dimnames = list(gene.names, cell.names))
  if (save_mtx) {
    save_path <- normalizePath(save_path, mustWork = FALSE)
    if (!dir.exists(save_path)) {
      dir.create(save_path)
    }
    save_cellranger(mat, save_path, ...)
    invisible(mat)
  } else {
    return(mat)
  }
}
```

Here is the save_cellranger function: 
https://github.com/BUStools/BUSpaRse/blob/ca0236611c82aac2281c0ffcfc1c9827a9c65bf5/R/utils.R#L104-L122

**Comment by LTLA** [comment]
Just wanted to mention that there's nothing special in _SingleCellExperiment_ with respect to sparse matrices; those will work off the shelf with your standard _SummarizedExperiment_. You only need a SCE if you want a better place to store stuff like reduced dimensions, spike-in information, etc.

**Comment by mikelove** [comment]
This is mostly done. Alevin work continues but not related to this thread
