### ISSUE TITLE
Error in H5Fopen

### ISSUE THREAD

**Issue by uso2015** [mikelove/tximport#27]
Hi,mikelove 
     I used the kallisto  for RNA-seq, then import the result "*.h5" by the tximport tools, but I get the following error:
  Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) :
  HDF5. File accessibilty. Unable to open file.
  
  I am not sure if this is an issue with tximport or with my own data.

**Comment by mikelove** [comment]
This is a file access problem but also please post all support questions here in the future:

https://support.bioconductor.org
