### ISSUE TITLE
Importing transcript abundance datasets generated with Salmon 0.14.0

### ISSUE THREAD

**Issue by edoardobertolini** [mikelove/tximport#29]
Hi!
I have recently updated Salmon to the latest version (0.14.0) and I'm not anymore able to import Salmon outputs into R using the code
tximport(file, type = "salmon", txOut = TRUE, countsFromAbundance = "no")

This is the error that I get when I run the code above:

txi <- tximport(file, type = "salmon", txOut = TRUE, countsFromAbundance = "no")
reading in files with read_tsv
Error in readBin(bootCon, "integer", n = expected.n) :
  invalid 'n' argument

Any suggestion?
Thanks

Edo

**Comment by mikelove** [comment]
Would you mind posting to Bioc support site and include sessionInfo(). I mainly use GitHub for feature requests but like to have bugs etc reported at Bioc. Did you include bootstraps or Gibbs samples this time? Previously?

**Comment by mikelove** [comment]
Looks like Rory has a fix, I’ll pull that in a minute, and then I’ll provide code to test the fix on your end

**Comment by edoardobertolini** [comment]
Thanks!
I've included bootstraps when I run Salmon.
I will post this to Bioc support.
*Edoardo*



Il giorno lun 10 giu 2019 alle ore 13:05 Mike Love <notifications@github.com>
ha scritto:

**Comment by mikelove** [comment]
Here's how you can test the new fixed version, which Rory just contributed.

```
library(devtools)
install_github("mikelove/tximport")
```

Let me know if this fixes it. Thanks!

**Comment by edoardobertolini** [comment]
It works!
Thanks
