### ISSUE TITLE
Error in importing RSEM gene level result files

### ISSUE THREAD

**Issue by Duanzpwt** [mikelove/tximport#33]
I used this line of code to import RSEM ".gene.results" files:
txi.rsem <- tximport(files, type = "rsem", txIn = FALSE, txOut = FALSE)，and it returns error："all(c(geneIdCol, abundanceCol, lengthCol) %in% names(raw)) is not TRUE" ，
then i  explicitly define the column names like in the line of code below：
txi.rsem <- tximport("ceshi2.tsv", type = "rsem", txIn = FALSE, txOut = FALSE, tx2gene = NULL, countsFromAbundance = "no", varReduce = FALSE, dropInfReps = FALSE, ignoreTxVersion = FALSE, geneIdCol = "gene_id", txIdCol = "transcript_id", abundanceCol = "TPM", countsCol = "expected_count", lengthCol = "effective_length")
it returns the same error.
my files are just like the picture :
![QQ截图20190617121153](https://user-images.githubusercontent.com/51895551/59578105-34e21900-90f9-11e9-9416-cb0d487ee14c.jpg)

**Comment by aankit01-art** [comment]
Hi Duanzpwt,

Is it possible to know how the above error got solved ?

I am also experiencing the same error like below:

Error in tximport(files, type = "salmon", tx2gene = tx2gene, importer = my_read_tsv,  : 
all(c(abundanceCol, countsCol, lengthCol) %in% names(raw)) is not TRUE

Thanks
