### ISSUE TITLE
Outdated vignette?

### ISSUE THREAD

**Issue by TobiTekath** [mikelove/tximport#34]
I just wanted to indicate, that the currently linked bioconductor vignette is not the same as the tximport.Rmd in this repository.
Especially the edgeR-part in the vignette seems to be outdated in comparison to the .Rmd file (the changes were committed before the 26th of June, which is the date of the linked vignette).
Or am I missing something?

**Comment by mikelove** [comment]
Bioc has two branches, release and devel. This repo is linked with devel but release is updated every 6 months (April and Oct).
