### ISSUE TITLE
Move Alevin import code to C++

### ISSUE THREAD

**Issue by mikelove** [mikelove/tximport#35]
Plans to move the Alevin import code to C++, big improvements in speed shown by @k3yavi 

Code will probably go into _fishpond_ as it is designed to be a package for Salmon to Bioc methods and utilities.

**Comment by mikelove** [comment]
Close with 0943b3d36b9f16ba528e07434454897ccbbafa24

**Comment by k3yavi** [comment]
w00t !

**Comment by mikelove** [comment]
For 30k cells, @k3yavi's code appears to be 40x faster than the R code.
