### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by smoe** [mikelove/tximport#36]
Hello,
May I ask for release tags?  Tximport is part of the pigx-rnaseq pipeline (https://github.com/BIMSBbioinfo/pigx_rnaseq/) that I have just packaged for Debian. With release tags we would be informed about updates. The version on BioConductor is 1.12.3, which we could also use if that is what you prefer.
Many thanks
Steffen

**Comment by mikelove** [comment]
Good question. This GitHub repository of `tximport` is mainly for facilitating viewing the source code, as well as the occasional feature request (most software questions are reported on the Bioc support site). 

So the primary releases should be drawn not from GitHub but from the Bioconductor git server which is the canonical home for tximport and other packages. I don't think Bioconductor adds release tags however. That would be a good question for the Bioconductor developer mailing list.
