### ISSUE TITLE
ignoreAfterBar does not apply with txOut=T and countsFromAbundance != "no"

### ISSUE THREAD

**Issue by karl616** [mikelove/tximport#38]
Thank you for an eminent and very convenient software.

I'm importing kallisto data from h5 files and want output the transcripts. With Gencode as a reference this comes with an inconvenient transcript naming adding |-separated information after the transcript ID. Exporting genes, this is handled by the ignoreAfterBar flag, but this never takes effect when exporting transcripts:

https://github.com/mikelove/tximport/blob/master/R/tximport.R#L578-L595

Is this intentional?

**Comment by mikelove** [comment]
Yes, essentially you can modify transcript names with a one liner as you like. The reason that the argument exists is because the transcript-to-gene matching occurs inside the function.
