### ISSUE TITLE
Import processed data

### ISSUE THREAD

**Issue by koenvandenberge** [mikelove/tximport#42]
I am working with public data that's been quantified (using `kallisto`) on the transcript level. However, I am rather interested in a gene-level analysis and was hoping to aggregate the data to the gene level. I only have the processed transcript-level estimated counts matrix available, and an object to link transcripts to genes. I should also be able to get the transcript lengths.

However, I did not find documentation on how to do the aggregation using `tximport` if we can't get our hands on the quant files. Suppose we have the count matrix, tx2gene object and the transcript lengths, is it recommended to try and recreate the list structure created as output from `tximport`?

**Comment by mikelove** [comment]
In the man pages there should be a function summarizeToGene that works on lists of matrices. It’s been exported for a few releases, but it’s not discussed in vignette i think.

**Comment by koenvandenberge** [comment]
Thanks, and sorry but I missed the issue on posting to the Bioconductor support site here. I will close and continue on Bioconductor support site if I can't get that to work.

**Comment by mikelove** [comment]
No worries. Let me know if you have any issues.
