### ISSUE TITLE
Recomended count scaling method for DTU analysis

### ISSUE THREAD

**Issue by kvittingseerup** [mikelove/tximport#43]
When using tximport to import transcript level quantification with the end goal of performing DTU analysis which of the 4 count scaling methods would you recommend? (Asking since dtuScaledTPM was introduced after the [Swimming downstream paper](https://f1000research.com/articles/7-952/v3) recommending "scaledTPM").

**Comment by mikelove** [comment]
`scaledTPM` or `dtuScaledTPM` are the ones that are appropriate for DTU, because the counts remain proportional to the TPMs within gene.

They are very similar. The latter keeps the scaled counts closer to the original counts however, which may be desirable.

**Comment by kvittingseerup** [comment]
Thanks
