### ISSUE TITLE
Returns TPM when abundanceCol is set to any value for type='rsem'

### ISSUE THREAD

**Issue by csmith-pact** [mikelove/tximport#44]
Desired behavior is to return FPKMs when abundanceCol='FPKM' and throw an error if an invalid value is set - TPMs are returned regardless of its value currently without a warning to the user. 

e.g.
tximport(files, type = "rsem", txIn = FALSE, txOut = FALSE, abundanceCol = 'FPKM')

tximport_1.18.0

**Comment by mikelove** [comment]
I think this one will resolve:

https://support.bioconductor.org/p/134119/#134121
