### ISSUE TITLE
Move `DESeqDataSetFromTximport` into tximport for now?

### ISSUE THREAD

**Issue by mdshw5** [mikelove/tximport#7]
Since the `DESeqDataSetFromTximport` function is only available in the development version of DESeq2, does it make sense to move the function into tximport until the next DESeq2 stable release?

**Comment by mikelove** [comment]
I'd rather it stay in its native environment. Some users work in the devel branch so testing there makes sense.

If you want to use it without installing R-devel you can grab the code here:

https://github.com/Bioconductor-mirror/DESeq2/blob/master/R/AllClasses.R#L318-L333

**Comment by mdshw5** [comment]
Great, thanks. 

Matt Shirley
